version: "3"

services:
  app:
    container_name: docker-note-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 24331
    ports:
      - "24331:24331"
